# --- CONFIGURACIÓN DE BASE DE DATOS ---
# Driver de Postgres
quarkus.datasource.db-kind=postgresql
# Usuario DB
quarkus.datasource.username=postgres
# Clave DB
quarkus.datasource.password=postgres
# URL de la DB (Asegúrate de que la DB pweb_db exista o cámbiala según tu necesidad)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pweb_db

# --- HIBERNATE / JPA ---
# Crea/Actualiza tablas automáticamente
quarkus.hibernate-orm.database.generation=update
# Muestra SQL en consola para debug
quarkus.hibernate-orm.log.sql=true

# --- SEGURIDAD OAUTH2 / JWT ---
# Ubicación de la llave PÚBLICA (debe ser la pareja de la privateKey.pem del Auth Server)
mp.jwt.verify.publickey.location=publicKey.pem
# IMPORTANTE: Este debe coincidir EXACTAMENTE con el auth.issuer del Auth Server
mp.jwt.verify.issuer=global-auth

# --- RED Y RUTAS ---
# Prefijo de las URLs para este microservicio
quarkus.resteasy.path=/academia/api/v1.0
# Puerto del servidor (distinto al 8082 para que no choquen)
quarkus.http.port=8081

# --- CORS (Conexión con Vue) ---
# Permite conexión con el Front
quarkus.http.cors.enabled=true
# Acepta peticiones de cualquier origen (en producción esto se restringe)
quarkus.http.cors.origins=*
